name: CI/CD for tq_bot

on:
  release:
    types: [created]
    branches:
      - main
      - dev

jobs:
  tq_bot-push:
    name: Pushing tq_bot images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/tq_bot
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=ref,event=tag

      - name: timetable build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.tq_bot
          push: true
          tags: ${{ steps.meta.outputs.tags }}